DROP DATABASE IF EXISTS stat;
CREATE DATABASE stat;
USE stat;

CREATE USER 'rootless'@'%' IDENTIFIED BY 'statapp1337';
GRANT ALL PRIVILEGES ON stat.* TO 'rootless'@'%';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS Evaluation;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Operator;
DROP TABLE IF EXISTS User;


CREATE TABLE User (
	UserId SMALLINT AUTO_INCREMENT,
    UserName VARCHAR(50) NOT NULL,
    UserLogin VARCHAR(10) NOT NULL,
    UserPin VARCHAR(10) NOT NULL,
    ValidFrom DATETIME DEFAULT CURRENT_TIMESTAMP,
    ValidTo DATETIME,
    PRIMARY KEY (UserId)
);

DELIMITER //
CREATE TRIGGER set_default_datetime_before_insert
BEFORE INSERT ON User
FOR EACH ROW
BEGIN
    IF NEW.ValidTo IS NULL THEN
        SET NEW.ValidTo = NOW() + INTERVAL 1 YEAR;
    END IF;
END //
DELIMITER ;

CREATE TABLE Event (
	EventId SMALLINT AUTO_INCREMENT,
    UserId SMALLINT NOT NULL,
    EventName VARCHAR(100) NOT NULL,
    CreateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES User(UserId),
    PRIMARY KEY (EventId)
);

CREATE TABLE Operator (
	OperatorId SMALLINT AUTO_INCREMENT,
    UserId SMALLINT NOT NULL,
    OperatorName VARCHAR(50),
    FOREIGN KEY (UserId) REFERENCES User(UserId),
    PRIMARY KEY (OperatorId)
);

CREATE TABLE Evaluation (
	EvalId MEDIUMINT AUTO_INCREMENT,
    EventId SMALLINT NOT NULL,
	OperatorId SMALLINT NOT NULL,
    EvalValue TINYINT NOT NULL,
    CHECK (EvalValue BETWEEN 1 AND 5),
    EvalTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EventId) REFERENCES Event(EventId),
    FOREIGN KEY (OperatorId) REFERENCES Operator(OperatorId),
    PRIMARY KEY (EvalId)
);
